#!/bin/bash

# ============================================================================
# Greengrass Core Installation Script (Infrastructure as Code)
# ============================================================================
# This script reinstalls AWS IoT Greengrass Core with new Thing credentials
# Generated by Terraform - DO NOT EDIT MANUALLY
# ============================================================================

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration (from Terraform)
THING_NAME="${thing_name}"
THING_GROUP="${thing_group}"
REGION="${region}"
IOT_ENDPOINT="${iot_endpoint}"
CREDS_ENDPOINT="${creds_endpoint}"
POLICY_NAME="${policy_name}"
TES_ROLE_NAME="${tes_role_name}"
TES_ROLE_ALIAS="${tes_role_alias}"

# Certificate paths
CERT_FILE="${cert_file}"
PRIVATE_KEY_FILE="${private_key_file}"
ROOT_CA_FILE="${root_ca_file}"

# Greengrass paths
GG_ROOT="/greengrass/v2"
GG_INSTALLER="$GG_ROOT/GreengrassCore/lib/Greengrass.jar"

# ============================================================================
# Functions
# ============================================================================

log_info() {
    echo -e "$${GREEN}[INFO]$${NC} $1"
}

log_warn() {
    echo -e "$${YELLOW}[WARN]$${NC} $1"
}

log_error() {
    echo -e "$${RED}[ERROR]$${NC} $1"
}

log_step() {
    echo -e "$${BLUE}[$1/$2]$${NC} $3"
}

check_root() {
    if [ "$EUID" -ne 0 ]; then
        log_error "This script must be run as root (use sudo)"
        exit 1
    fi
}

print_header() {
    echo ""
    echo "================================================================"
    echo "  AWS IoT Greengrass Core Reinstallation"
    echo "================================================================"
    echo ""
    echo "Configuration:"
    echo "  Thing Name:     $THING_NAME"
    echo "  Thing Group:    $THING_GROUP"
    echo "  Region:         $REGION"
    echo "  IoT Endpoint:   $IOT_ENDPOINT"
    echo "  Policy:         $POLICY_NAME"
    echo ""
    echo "================================================================"
    echo ""
}

verify_certificates() {
    log_step 1 10 "Verifying certificates..."

    if [ ! -f "$CERT_FILE" ]; then
        log_error "Certificate not found: $CERT_FILE"
        exit 1
    fi

    if [ ! -f "$PRIVATE_KEY_FILE" ]; then
        log_error "Private key not found: $PRIVATE_KEY_FILE"
        exit 1
    fi

    if [ ! -f "$ROOT_CA_FILE" ]; then
        log_error "Root CA not found: $ROOT_CA_FILE"
        exit 1
    fi

    log_info "✓ All certificates found"
}

stop_greengrass() {
    log_step 2 10 "Stopping Greengrass service..."

    if systemctl is-active --quiet greengrass.service 2>/dev/null; then
        systemctl stop greengrass.service
        sleep 3
        log_info "✓ Greengrass service stopped"
    else
        log_warn "Greengrass service not running"
    fi
}

backup_current_installation() {
    log_step 3 10 "Backing up current installation..."

    BACKUP_DIR="$GG_ROOT.backup-$(date +%Y%m%d-%H%M%S)"

    if [ -d "$GG_ROOT" ]; then
        cp -r "$GG_ROOT" "$BACKUP_DIR"
        log_info "✓ Backup created: $BACKUP_DIR"
    else
        log_warn "No existing installation to backup"
    fi
}

clean_old_installation() {
    log_step 4 10 "Cleaning old installation..."

    # Remove config and deployments (keep GreengrassCore installer)
    if [ -d "$GG_ROOT/config" ]; then
        rm -rf "$GG_ROOT/config"
        log_info "✓ Removed old config"
    fi

    if [ -d "$GG_ROOT/deployments" ]; then
        rm -rf "$GG_ROOT/deployments"
        log_info "✓ Removed old deployments"
    fi

    if [ -d "$GG_ROOT/work" ]; then
        rm -rf "$GG_ROOT/work"
        log_info "✓ Removed old work directory"
    fi

    # Remove old certificates
    rm -f "$GG_ROOT/thingCert.crt"
    rm -f "$GG_ROOT/privKey.key"
    rm -f "$GG_ROOT/rootCA.pem"

    log_info "✓ Old installation cleaned"
}

copy_certificates() {
    log_step 5 10 "Copying new certificates..."

    cp "$CERT_FILE" "$GG_ROOT/thingCert.crt"
    cp "$PRIVATE_KEY_FILE" "$GG_ROOT/privKey.key"
    cp "$ROOT_CA_FILE" "$GG_ROOT/rootCA.pem"

    # Set proper permissions
    chown root:ggc_group "$GG_ROOT/thingCert.crt"
    chown root:ggc_group "$GG_ROOT/privKey.key"
    chown root:ggc_group "$GG_ROOT/rootCA.pem"

    chmod 644 "$GG_ROOT/thingCert.crt"
    chmod 640 "$GG_ROOT/privKey.key"
    chmod 644 "$GG_ROOT/rootCA.pem"

    log_info "✓ Certificates copied and permissions set"
}

create_config_yaml() {
    log_step 6 10 "Creating Greengrass configuration..."

    mkdir -p "$GG_ROOT/config"

    cat > "$GG_ROOT/config/config.yaml" <<EOF
---
system:
  certificateFilePath: "$GG_ROOT/thingCert.crt"
  privateKeyPath: "$GG_ROOT/privKey.key"
  rootCaPath: "$GG_ROOT/rootCA.pem"
  rootpath: "$GG_ROOT"
  thingName: "$THING_NAME"
services:
  aws.greengrass.Nucleus:
    componentType: "NUCLEUS"
    version: "2.16.0"
    configuration:
      awsRegion: "$REGION"
      iotRoleAlias: "$TES_ROLE_ALIAS"
      iotDataEndpoint: "$IOT_ENDPOINT"
      iotCredEndpoint: "$CREDS_ENDPOINT"
      runWithDefault:
        posixUser: "ggc_user:ggc_group"
EOF

    chmod 644 "$GG_ROOT/config/config.yaml"
    log_info "✓ Configuration file created"
}

run_installer() {
    log_step 7 10 "Running Greengrass installer..."

    log_info "Installer command:"
    echo "  java -Droot=\"$GG_ROOT\" -Dlog.store=FILE \\"
    echo "    -jar $GG_INSTALLER \\"
    echo "    --aws-region $REGION \\"
    echo "    --thing-name $THING_NAME \\"
    echo "    --thing-group-name $THING_GROUP \\"
    echo "    --thing-policy-name $POLICY_NAME \\"
    echo "    --tes-role-name $TES_ROLE_NAME \\"
    echo "    --tes-role-alias-name $TES_ROLE_ALIAS \\"
    echo "    --component-default-user ggc_user:ggc_group \\"
    echo "    --provision false \\"
    echo "    --setup-system-service true \\"
    echo "    --deploy-dev-tools true"
    echo ""

    # Run installer with --provision false (use existing certificates)
    java -Droot="$GG_ROOT" -Dlog.store=FILE \
      -jar "$GG_INSTALLER" \
      --aws-region "$REGION" \
      --thing-name "$THING_NAME" \
      --thing-group-name "$THING_GROUP" \
      --thing-policy-name "$POLICY_NAME" \
      --tes-role-name "$TES_ROLE_NAME" \
      --tes-role-alias-name "$TES_ROLE_ALIAS" \
      --component-default-user ggc_user:ggc_group \
      --provision false \
      --setup-system-service true \
      --deploy-dev-tools true

    log_info "✓ Greengrass installer completed"
}

start_greengrass() {
    log_step 8 10 "Starting Greengrass service..."

    systemctl daemon-reload
    systemctl enable greengrass.service
    systemctl start greengrass.service

    sleep 5

    if systemctl is-active --quiet greengrass.service; then
        log_info "✓ Greengrass service started successfully"
    else
        log_error "Failed to start Greengrass service"
        systemctl status greengrass.service --no-pager
        exit 1
    fi
}

verify_installation() {
    log_step 9 10 "Verifying installation..."

    # Wait for Greengrass to fully initialize
    log_info "Waiting for Greengrass to initialize (30 seconds)..."
    sleep 30

    # Check components
    if [ -x "$GG_ROOT/bin/greengrass-cli" ]; then
        log_info "Component list:"
        "$GG_ROOT/bin/greengrass-cli" component list | head -20
    else
        log_warn "Greengrass CLI not ready yet"
    fi
}

print_summary() {
    log_step 10 10 "Installation completed!"

    echo ""
    echo "================================================================"
    echo "  INSTALLATION SUMMARY"
    echo "================================================================"
    echo ""
    echo "✓ Greengrass reinstalled successfully"
    echo "✓ Thing Name:    $THING_NAME"
    echo "✓ Region:        $REGION"
    echo "✓ Thing Group:   $THING_GROUP"
    echo ""
    echo "Backup Location: $BACKUP_DIR"
    echo ""
    echo "================================================================"
    echo "  NEXT STEPS"
    echo "================================================================"
    echo ""
    echo "1. Check service status:"
    echo "   sudo systemctl status greengrass.service"
    echo ""
    echo "2. List components:"
    echo "   sudo /greengrass/v2/bin/greengrass-cli component list"
    echo ""
    echo "3. View logs:"
    echo "   sudo tail -f /greengrass/v2/logs/greengrass.log"
    echo ""
    echo "4. Check Thing on AWS:"
    echo "   aws iot describe-thing --thing-name $THING_NAME --region $REGION"
    echo ""
    echo "5. Verify Shadow sync:"
    echo "   aws iot-data get-thing-shadow --thing-name $THING_NAME --region $REGION /dev/stdout"
    echo ""
    echo "================================================================"
    echo ""
}

# ============================================================================
# Main Installation Flow
# ============================================================================

main() {
    check_root
    print_header

    # Confirmation prompt
    read -p "Proceed with Greengrass reinstallation? (yes/no): " -r
    echo
    if [[ ! $REPLY =~ ^[Yy]es$ ]]; then
        log_warn "Installation cancelled by user"
        exit 0
    fi

    verify_certificates
    stop_greengrass
    backup_current_installation
    clean_old_installation
    copy_certificates
    create_config_yaml
    run_installer
    start_greengrass
    verify_installation
    print_summary
}

# Run main function
main "$@"
